SELECT SURFACE_GEOMETRY.ID
FROM CITYOBJECT INNER JOIN SURFACE_GEOMETRY
ON CITYOBJECT.ID = SURFACE_GEOMETRY.CITYOBJECT_ID
WHERE CITYOBJECT.GMLID = 'WSLod2e9e7aa20-5f7a-4a4a-ac9c-c0221d8e19dd'
AND SURFACE_GEOMETRY.GEOMETRY IS NOT NULL;

--SELECT ST_3DExtent(GEOMETRY) As b3extent
--FROM SURFACE_GEOMETRY 
--WHERE SURFACE_GEOMETRY.ID = 97162;

--97161
--97162

WITH t1 as (
--SELECT ST_Union(ST_SnapToGrid(GEOMETRY,0.0001)) AS Merged_Facade_geom
SELECT ST_Union(GEOMETRY) AS Merged_Facade_geom
FROM CITYOBJECT INNER JOIN SURFACE_GEOMETRY
ON CITYOBJECT.ID = SURFACE_GEOMETRY.CITYOBJECT_ID
WHERE SURFACE_GEOMETRY.ID = 97161 OR SURFACE_GEOMETRY.ID = 97162
GROUP BY CITYOBJECT.GMLID)

SELECT ST_3DExtent(Merged_Facade_geom)
FROM t1;