/*

--RoofSurfaces of planned buildings:
SELECT *
FROM SURFACE_GEOMETRY INNER JOIN CITYOBJECT
ON SURFACE_GEOMETRY.CITYOBJECT_ID = CITYOBJECT.ID
WHERE CITYOBJECT.OBJECTCLASS_ID = 33 AND
(CITYOBJECT.GMLID LIKE 'pb-rs-%' OR CITYOBJECT.GMLID LIKE 'pb-rs%')

-- RoofSurfaces of existing buildings:
SELECT *
FROM SURFACE_GEOMETRY INNER JOIN CITYOBJECT
ON SURFACE_GEOMETRY.CITYOBJECT_ID = CITYOBJECT.ID
WHERE CITYOBJECT.OBJECTCLASS_ID = 33 AND
(CITYOBJECT.GMLID NOT LIKE 'pb-rs-%' AND CITYOBJECT.GMLID NOT LIKE 'pb-rs%')

*/


/*
--WallSurfaces of planned buildings:
SELECT *
FROM SURFACE_GEOMETRY INNER JOIN CITYOBJECT
ON SURFACE_GEOMETRY.CITYOBJECT_ID = CITYOBJECT.ID
WHERE CITYOBJECT.OBJECTCLASS_ID = 34 AND
(CITYOBJECT.GMLID LIKE 'pb-ws-%' OR CITYOBJECT.GMLID LIKE 'pb-wslod3%')
*/



/*
--WallSurfaces of existing buildings:
SELECT *
FROM SURFACE_GEOMETRY INNER JOIN CITYOBJECT
ON SURFACE_GEOMETRY.CITYOBJECT_ID = CITYOBJECT.ID
WHERE CITYOBJECT.OBJECTCLASS_ID = 34 AND
(CITYOBJECT.GMLID NOT LIKE 'pb-ws-%' AND CITYOBJECT.GMLID NOT LIKE 'pb-wslod3%')
*/




/*
--GroundSurfaces of planned buildings:
SELECT *
FROM SURFACE_GEOMETRY INNER JOIN CITYOBJECT
ON SURFACE_GEOMETRY.CITYOBJECT_ID = CITYOBJECT.ID
WHERE CITYOBJECT.OBJECTCLASS_ID = 35 AND
(CITYOBJECT.GMLID LIKE 'pb-gs%' OR CITYOBJECT.GMLID LIKE 'pb-gslod3%')
*/



/*
--GroundSurfaces of existing buildings:
SELECT *
FROM SURFACE_GEOMETRY INNER JOIN CITYOBJECT
ON SURFACE_GEOMETRY.CITYOBJECT_ID = CITYOBJECT.ID
WHERE CITYOBJECT.OBJECTCLASS_ID = 35 AND
(CITYOBJECT.GMLID NOT LIKE 'pb-gs%' AND CITYOBJECT.GMLID NOT LIKE 'pb-gslod3%')
*/




