
DELETE FROM TEXTUREPARAM 
WHERE TEXTUREPARAM.SURFACE_GEOMETRY_ID IN (
SELECT TEXTUREPARAM.SURFACE_GEOMETRY_ID
FROM TEXTUREPARAM INNER JOIN SURFACE_GEOMETRY
ON TEXTUREPARAM.SURFACE_GEOMETRY_ID = SURFACE_GEOMETRY.ID
INNER JOIN CITYOBJECT 
ON SURFACE_GEOMETRY.CITYOBJECT_ID = CITYOBJECT.ID
WHERE CITYOBJECT.OBJECTCLASS_ID = 38);
