--Populate APPEAR_TO_SURFACE_DATA table with values
/*
--Add all colors related to OA_LOD3 to corresponding theme
INSERT INTO citydb.APPEAR_TO_SURFACE_DATA
VALUES (0, 1);

INSERT INTO citydb.APPEAR_TO_SURFACE_DATA
VALUES (1, 1);

INSERT INTO citydb.APPEAR_TO_SURFACE_DATA
VALUES (2, 1);

INSERT INTO citydb.APPEAR_TO_SURFACE_DATA
VALUES (3, 1);

INSERT INTO citydb.APPEAR_TO_SURFACE_DATA
VALUES (4, 1);

INSERT INTO citydb.APPEAR_TO_SURFACE_DATA
VALUES (5, 1);

INSERT INTO citydb.APPEAR_TO_SURFACE_DATA
VALUES (6, 1);

INSERT INTO citydb.APPEAR_TO_SURFACE_DATA
VALUES (7, 1);

INSERT INTO citydb.APPEAR_TO_SURFACE_DATA
VALUES (8, 1);





-- Add colors for planned buildings to corresponding theme
INSERT INTO citydb.APPEAR_TO_SURFACE_DATA
VALUES (9, 1);

INSERT INTO citydb.APPEAR_TO_SURFACE_DATA
VALUES (10, 1);

INSERT INTO citydb.APPEAR_TO_SURFACE_DATA
VALUES (11, 1);

*/


--AIrr textures:
--INSERT INTO citydb.APPEAR_TO_SURFACE_DATA
--VALUES (18, 3); --SURFACE_DATA.ID (TEXTURE ID), APPEARANCE.ID (THEME ID for AIrr)


